name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'jsbt v0.3.3' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@2943fdf410ec5a74080ebf596ad1b0decbe89927
    with:
      runs-on: 'ubuntu-24.04'
      submodules: true
